name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        node_version: [6,7]
    runs-on: ${{matrix.os}}
    steps:
      - name: Node Version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node_version: ${{matrix.node_version}}
      - name: Node Version
        run: node -v
